# どうなるかわかんないけどENUMにするとめんどくさいやつの定数とかここに置く
# まだ組み込んでいない

# TYPE
TYPE_MEMO = 1
TYPE_TASK = 2
TYPE_SCEDURE = 3
TYPE_PROJECT = 4

# PRIORITY
PRIORITY_NONE = 0
PRIORITY_LOW = 1
PRIORITY_NORMAK = 2
PRIORITY_HIGH = 3
PRIORITY_YABAI = 4

# STATUS
STATUS_NEW = 0
STATUS_DOING = 1
STATUS_DONE = 2
STATUS_FAILED = 3